# This is an example Atlassian Bamboo CI configuration that demonstrates how to
# use github-actions-runner to run a GitHub Actions workflow in a Bamboo CI job.
#
# Check out .github/workflows/example.yml to see what workflow this Bamboo job
# actually runs.
#
# This example demonstrates how to:
# * Trigger a workflow run.
# * Download the artifacts produced by the workflow.
# * Pass secrets from the CI to the workflow.
---
version: 2
plan:
  project-key: AJL
  key: GHACTIONSRUNEXAMPLE
  name: github-actions-runner - example
variables:
  # Using github-actions-runner Docker image for the latest stable version.
  # latest-ci docker image does not have any entrypoint and has the
  # runner installed.
  docker: ghcr.io/adguardteam/githubactionsrunner:latest-ci

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.docker}
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Make sure the script fails on any error.
            set -e

            # Combine stderr and stdout for consistent log output.
            exec 2>&1

            GITHUB_TOKEN=${bamboo.githubActionsRunnerPassword} github-actions-runner run-action \
              --repo AdguardTeam/GithubActionsRunner \
              --branch "${bamboo_planRepository_branchName}" \
              --rev "${bamboo_planRepository_revision}" \
              --workflow example.yml \
              --artifacts-path .
              --secret SECRET_KEY=SECRET_VALUE
  # The artifacts produced by the workflow are downloaded and shared with the
  # Bamboo CI job. These artifacts can be then shared with other unrelated
  # Bamboo builds.
  artifacts:
    - name: example.txt
      pattern: example.txt
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
