# Example workflow for github-actions-runner
name: Example

on:
  workflow_dispatch:
    inputs:
      ## !NOTE: This input is required to identify the workflow run
      id:
        type: 'string'
        description: 'Unique identifier for the workflow run. Needed for github-actions-runner to identify the run.'

## !NOTE: This name is required to identify the workflow run
run-name: ${{github.workflow}} [ID:${{ inputs.id }}]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
      - name: Run bash commands
        shell: bash
        run: |
          ls -alt

          # Building package artifact
          echo "example" > example.txt

          # Show that secrets are encoded
          echo "Secret is ${{ secrets.SECRET_KEY }}"
      - name: Save archived package
        uses: actions/upload-artifact@v4
        with:
          name: example.txt
          path: ./example.txt
