# Tests build
name: Test

env:
  NODE_VERSION: 20

on:
  workflow_dispatch:
    inputs:
      id:
        type: 'string'
        description: 'Unique identifier for the workflow run. Needed for github-actions-runner'

## Required for github-actions-runner
run-name: ${{github.workflow}} [ID:${{ inputs.id }}]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Run bash commands
        shell: bash
        run: |
          ls -alt

          # install deps
          pnpm install

          # Linting package
          pnpm lint

          # Testing package
          pnpm test

          # Testing that it can be built
          pnpm build
